---

is_debug: true
auth:
  login: test123
  password_hash: b1b3773a05c0ed0176787a4f1574ff0075f7521e # Encrypted 'qwerty'
  salt: # h1$2Ej#jd5e23jkl2F
  secret: kdIewjDi#q$L#dF$%wle
listen:
  port: 8626 # If 0 then automatic port selection
